### PR TITLE
Add windows install instructions

### PR DESCRIPTION
**Pull request by ehayes2000**
Specify requirement for use on windows.

### CODE REVIEW

**Comment by LudovicRousseau** [comment]
You do not have to install OpenSC on Windows (or any other OS) to use PyKCS11.
OpenSC is not the only PKCS#11 library.

Or I missed something?

**Comment by ehayes2000** [comment]
You are right there are other PKCS#11 implementations. 

On windows PKCS#11 is not installed by default and `PyKCS11` cannot be imported until a PKCS#11 implementation is added to the path. After spending a considerable amount of time yesterday resolving this import issue I amended the README with my fix. There may be a more accurate description of this fix, but regardless it should be made clear that PKCS#11 must be installed with this library.

**Comment by LudovicRousseau** [comment]
What do you mean by "`PyKCS11` cannot be imported"?

```
import PyKCS11
```
should always work.

**Comment by ehayes2000** [comment]
No. `import PyKCS11` did not work until I installed `OpenSC` I got an error stating that some module could not be found. I'm using a different computer to write this so I'll try to reproduce the issue for you tomorrow and provide more details. 

It looks like I should have made this an issue instead of a PR, my mistake.

**Pull request closed without merging**
