### PR TITLE
Use setuptools

### PR DESCRIPTION
**Pull request by fzonneveld**

### CODE REVIEW

**Comment by LudovicRousseau** [comment]
The build on Windows failed. See https://ci.appveyor.com/project/LudovicRousseau/pykcs11/builds/21829464

What is/are the benefit(s) of your changes?

**Comment by LudovicRousseau** [comment]
@fzonneveld any progress on the Windows investigation?

**Comment by fzonneveld** [comment]
Did some trick to get the install location (egg for setuptools) to perform the copy...

**Comment by LudovicRousseau** [comment]
Merged.
Thanks

**Comment by fzonneveld** [comment]
Thank you. Also had a look at swig, very helpful for interfacing python
with C.

Thanks Frank,

**Pull request closed without merging**
